### ISSUE TITLE
Don’t work with homey v2.0

### ISSUE THREAD

**Issue by rfiskvik** [TedTolboom/no.IDLock#12]
After update to Homey v2.0 nothing works anymore. Will not lock/ unlock if make a flow.
Also battery indicator shows 100% all the time, and still drains battery.
Otherwise a great app!!
Id Lock 101

**Comment by TedTolboom** [comment]
Thanks for reporting.
At this moment I, Homey SW v2.0.0 has a bug where the trigger card don’t work properly (although working properly for 1.5.13). 

This is reported for several apps and Athom is aware of if and looking for a solution. No timing mentioned yet when this is resolved.

So unfortunately we’ll have to wait for Athom to fix this issue.

**Comment by TedTolboom** [comment]
@rfiskvik can you check if the issue persists with rc.9 or higher?

**Comment by rfiskvik** [comment]
Hello. Seems to be working perfect:)
Thanks a lot 👍

Best regards, Ronny Fiskvik

4. jan. 2019 kl. 09:31 skrev dT <notifications@github.com<mailto:notifications@github.com>>:


@rfiskvik<https://github.com/rfiskvik> can you check if the issue persists with rc.9 or higher?

**Comment by johnniemalm** [comment]
Hi Ted, noticed that batterydrain start again, on one of my locks, the one that i used all the time, it whent from 60 to 40 % in 2 days

**Comment by rfiskvik** [comment]
👍
