### ISSUE TITLE
Major problems with v1.2.1

### ISSUE THREAD

**Issue by perrra1982** [TedTolboom/no.IDLock#20]
Since the update to 1.2.1 i have some major problems:
• The app keeps crasching every so often
• The tamper alarm triggers even though the door has only been unlocked and shortly thereafter 
• The heat alarm also triggers at the same time as the tamper alarm

I created a diagnostic report with id:
87995fc2-d5d2-4e3d-9997-a9165e4c729d

**Comment by TedTolboom** [comment]
@perrra1982 can you check if they are resolved with version 1.2.2?

**Comment by perrra1982** [comment]
Hello. Yes i will check it and get back to you

// Per

Skickat från min iPhone

**Comment by perrra1982** [comment]
Hello

It seems like the latest release fixed the other mentioned issues as well. So you can close the ticket :-)

Thanks for the speedy bugfix

// Per

Skickat från min iPhone

**Comment by maheldt** [comment]
Hi

What about battery consumption. After the latest release, my lock went from 70 to 25% in a week. Went back to 1.2.0

Marius

**Comment by perrra1982** [comment]
I have no battery consumption issues now
