### ISSUE TITLE
Firmware updates adds new features

### ISSUE THREAD

**Issue by mickem** [TedTolboom/no.IDLock#25]
Unless I read the change log incorrectly there are some new features.
Especially the "lock jammed" notification which would be nice to have.
But might be better to add individual issues for each feature request?

From z-wave changelog:
* Changed how ID lock 150 handles configuration parameter 2 “RFID Registration mode”.
* Added configuration report for Door audio volume (configuration parameter 4) and service pin mode (configuration parameter 7)
* Added values 0x07 “always mode” and 0xFE “disable mode” to configuration parameter 7 service pin mode.
* Changed configuration parameter 8 “Updater mode” and 9 “Master PIN mode”.
* Added several new notification events for “Access Control” (0x06). Notifications for different lock types, add and delet credentials and lock jammed alarm added.
* Moved remote unlock from “keypad unlock operation” with identifier 0x00, to “RF unlock operation” with identifier 0x00.
* Changed Z-Wave identifiers for Master PIN, Service PIN, User PINs and RFID.

See full change log here: https://idlock.no/kundesenter/idl150updater-version/

**Comment by mickem** [comment]
According to the specification https://idlock.no/wp-content/uploads/2019/08/IDLock150_ZWave_UserManual_v3.02.pdf it is supposed to be:

Notification Type: Access Control (0x06), 
Event: Lock jammed (0x0B)

But I cant see that in either my z-wave log or after adding support to it to the application.
This is assuming jammed means the lock could not extend the bolt.

Can someone else confirm if they get a notification when the bolt i jammed?

**Comment by TedTolboom** [comment]
resolved in v.2.0.0
