### ISSUE TITLE
"Invalid field entry" with `index` over 9

### ISSUE THREAD

**Issue by runely** [TedTolboom/no.IDLock#30]
Can not add `Key` or `Code` with **index** higher than **9**!

1-9 is working okey, but from 10 and up i get `Invalid field entry`.

I have a tag added as slot nr **1** on the IDLock lock. This tag is presented as tag **26** in IDLock app (from `Who`). And when i cant add indexes over 9 i cant map them to a user in the app...

**IDLock app version**: 1.2.3
**Homey version**: 7.1.6
**IDLock firmware**: 1.5.9

![image](https://user-images.githubusercontent.com/25814673/143492755-3e446d3b-99fc-438b-b50b-357085f617c4.png)

![image](https://user-images.githubusercontent.com/25814673/143492840-bcbbf079-2a7e-4969-b3c7-69c13a871b76.png)

**Comment by joco73** [comment]
@runely I have updated my fork so it should work.
Info is that **_settings/index.html_**
had code like this:
` <span editable-number="code.index" e-name="index" e-form="rowform" e-min="1" e-max="9"
                                onbeforesave="checkNotEmpty($data)" e-required>
                                {{ code.index }}
                            </span>`


I have updated to this:
` <span editable-number="code.index" e-name="index" e-form="rowform" e-min="1" e-max="99"
                                onbeforesave="checkNotEmpty($data)" e-required>
                                {{ code.index }}
                            </span>`

Note the value of e-max.

**Comment by runely** [comment]
**THANK YOU SO MUCH** @joco73  👏

This works like a charm!

**Comment by Fotofantasten** [comment]
@TedTolboom

I installed the latest version today (1.2.3) after reciving my IDLock 150 yesterday and I get the same issue as the thread creator. Is there going to be an update in the app that solves the issue?

Best regards
Richard

**Comment by TedTolboom** [comment]
Resolved in v2.0.0
