### ISSUE TITLE
SDK3 and Homey Pro 2023

### ISSUE THREAD

**Issue by runely** [TedTolboom/no.IDLock#31]
Hi

Is this app going to be updated to SDK3 so it will work on the new Homey Pro 2023?

**Comment by rogerwesterbo** [comment]
Wondering about the same 🎉 or how could I contribute?

**Comment by TedTolboom** [comment]
I've just release v2.0.0 to the app store, providing SDK3 support for the Homey Pro (Early 2023).
See also https://community.homey.app/t/161/284

Closing this issue as resolved.
