### ISSUE TITLE
Add support to report on user (un)lock notifications

### ISSUE THREAD

**Issue by TedTolboom** [TedTolboom/no.IDLock#7]
Is it possible to add triggers by what user unlocked the door? 
This would help when you have kids to see when they get home or if te service pin is used ect.

**Comment by juw2** [comment]
Hi.
I have done some tests now and gather the logs. I have added info before the logging so you see what I have done.
Node.js.txt - Debug info from node.js window in run  mode
Developer.txt - Same info as above but from the developer web page.
Logging stdout and stderr.txt - Interesting that it says Battery: False, and it also has some errors in the end of the file.

Hope these help. If you need something else, please let me know.
It would alse be nice if it was possible to set Pin codes from the app, secction 4.6 in the document.

[Node.js.txt](https://github.com/TedTolboom/no.IDLock/files/2291444/Node.js.txt)
[Developer.txt](https://github.com/TedTolboom/no.IDLock/files/2291445/Developer.txt)
[Logging stdout and stderr.txt](https://github.com/TedTolboom/no.IDLock/files/2291446/Logging.stdout.and.stderr.txt)

**Comment by TedTolboom** [comment]
Great, this will help a lot!

Battery: False is correct.. yes, it's a battery powered device, but it is not sleeping... but Frequently Listening (FLiRS)..

Did you see any battery report from the lock?

According to the manual:
> The actual battery level is updated and sent after each unlock operation.
> Note: There is a short delay on the report sent after unlock operation

But I didn't see any battery reports after unlock reports...

I'll check to implement the reporting on user-codes...

section 4.6 will be a different chapter / update to implement... ok?

**Comment by juw2** [comment]
Hi.
In this file, I got the only info from the developer page regarding any Battery activity.

[Battery.txt](https://github.com/TedTolboom/no.IDLock/files/2292686/Battery.txt)

**Comment by TedTolboom** [comment]
It would even be excellent if you could provide me a developer page log of about 1 - 1.5 hours including the inclusion of the lock...  based on that, I can check if something goes wrong during inclusion...

Would that be possible?

**Comment by juw2** [comment]
Yes, I can fix that later today.

**Comment by juw2** [comment]
Now I have the files that includes inclusion and also 90-2h of data.
I have filtered the developer file with Node[160] after the inclusion part so it's less data.
If you need all data from all devices let me know. I have that saved as well.

[Inclusion and 2h data developer filtered Node 160.txt](https://github.com/TedTolboom/no.IDLock/files/2294627/Inclusion.and.2h.data.developer.filtered.Node.160.txt)
[Inclusion and 90min data in Node.js.txt](https://github.com/TedTolboom/no.IDLock/files/2294628/Inclusion.and.90min.data.in.Node.js.txt)

**Comment by juw2** [comment]
Please let me know if there is something else you need :)

**Comment by mickem** [comment]
I did some trial'n'error trying to add a card and got a bit on the way...

I can intercept "Access Control" notification messages, which contains information about how the lock was locked/unlocked (Keypad, Manual and RF). It also has a parameter (number) which I assume is the slot.

Unfortunately I cant get homey to trigger my card so I am missing something in the Homey infrastructure side...

If someone wants to tinker along I can push my code to a fork tomorrow...

But the gist of it is:

app.json
```
    "triggers": [{
                "id": "unlocked_by",
                "title": {
                    "en": "Unlocked by"
                },
                "args": [
                    {
                        "name": "device",
                        "type": "device",
                        "filter": "driver_id=IDlock150"
                    }
                ],
				"tokens": [
				  {
					"name": "src",
					"type": "string",
					"title": {
					  "en": "src",
					  "nl": "src"
					},
					"example": {
					  "en": "Button pressed (test)"
					}
				  },
				  {
					"name": "who",
					"type": "string",
					"title": {
					  "en": "who",
					  "nl": "who"
					},
					"example": {
					  "en": "Button pressed (test)"
					}
				  }
				]
            }]
```


As well as device.js:
```
		const unlockedBy = new Homey.FlowCardTriggerDevice('unlocked_by');
		unlockedBy.register();

// ...
// ... around line 103 in the notification handler
					if (report && report['Notification Type'] === 'Access Control' && report.hasOwnProperty('Event (Parsed)')) {
						if (report['Event (Parsed)'] === 'RF Unlock Operation' && report.hasOwnProperty('Event Parameter')) {
							unlockedBy.trigger( this, {src: report['Event Parameter'], who: report['Event Parameter']}, null );
							this.log("*** RF Unlock ***: ", report['Event Parameter']);
							return false;
						} else if (report['Event (Parsed)'] === 'Keypad Unlock Operation' && report.hasOwnProperty('Event Parameter')) {
							unlockedBy.trigger( this, {src: report['Event Parameter'], who: report['Event Parameter']}, null );
							this.log("*** Keypad Unlock ***: ", report['Event Parameter']);
							return false;
						} else if (report['Event (Parsed)'] === 'Manual Lock Operation') {
							unlockedBy.trigger( this, {src: report['Event Parameter'], who: ''}, null );
							this.log("*** Manual Lock ***");
							return false;
						} else if (report['Event (Parsed)'] === 'Manual Unlock Operation') {
							unlockedBy.trigger( this, {src: report['Event Parameter'], who: ''}, null );
							this.log("*** Manual Unlock ***");
							return false;
						} else {
							this.log("*** ???? unlock ***");
						}
```

**Comment by juw2** [comment]
@mickem, have you seen that @mansica has added functionality to see who unlocks a door and it has been merged into the Development branch.
With that solution it's possible to add names for each pin and card by configure the ID Lock APP from desktop app on a computer.

**Comment by TedTolboom** [comment]
version 1.2.0 (including registration of user codes for the ID lock 150, credits to @mansica) has been merged in master branch / uploaded to app store (for approval).

I'll close this issue awaiting the release to the app store
